## Ucitavanje i Sredjivanje Nizova Podataka

In [1]:
#ucitavanje potrebnih biblioteka
import pandas as pd
import numpy as np

In [2]:
#uvoz podataka
#sezona 23/24
df_23_4 = pd.read_csv("super-lig-2023.csv")
#sezona 24/25
df_24_5 = pd.read_csv("super-lig-2024.csv")
#sezona 25/6
df_25_6 = pd.read_csv("super-lig-2025.csv")

## Određivanje Duzine Trenutnoj Sezoni i Prikaz

In [3]:
#odrediti duzinu sezone - OBAVEZNO!!!
df_25_6 = df_25_6.head(117)
df_25_6.tail()

,Match Number,Round Number,Date,Location,Home Team,Away Team,Result
112,111,13,23/11/2025 17:00,Besiktas Stadyumu,Besiktas,Samsunspor,1 - 1
113,112,13,23/11/2025 17:00,Alanya Oba Stadium,Alanyaspor,Kasimpasa,1 - 2
114,116,13,23/11/2025 20:00,Rize City Stadium,Çaykur Rizespor,Fenerbahçe,2 - 5
115,110,13,24/11/2025 20:00,Konya Metropolitan Municipality Stadium,Konyaspor,Antalyaspor,0 - 0
116,113,13,24/11/2025 20:00,Basaksehir Fatih Terim Stadium,Istanbul Basaksehir,Trabzonspor,3 - 4

In [4]:
#sjedinjavanje ta tri df niza podataka - po osi jedan - odnosno uzduž
df_BL = pd.concat([df_23_4, df_24_5, df_25_6], axis=0)

In [5]:
#prikaz sjedinjenog niza podatak 
#tj. sve tri sezone u jednom nizu podataka u obliku df 
df_BL.tail()

,Match Number,Round Number,Date,Location,Home Team,Away Team,Result
112,111,13,23/11/2025 17:00,Besiktas Stadyumu,Besiktas,Samsunspor,1 - 1
113,112,13,23/11/2025 17:00,Alanya Oba Stadium,Alanyaspor,Kasimpasa,1 - 2
114,116,13,23/11/2025 20:00,Rize City Stadium,Çaykur Rizespor,Fenerbahçe,2 - 5
115,110,13,24/11/2025 20:00,Konya Metropolitan Municipality Stadium,Konyaspor,Antalyaspor,0 - 0
116,113,13,24/11/2025 20:00,Basaksehir Fatih Terim Stadium,Istanbul Basaksehir,Trabzonspor,3 - 4

## Predprocesovanje Niza Podataka

In [6]:
#Izbacivanje Nerelevantnih Osobina
df_BL = df_BL.drop(["Match Number","Round Number","Date","Location"],axis=1)
df_BL.shape

(839, 3)

In [7]:
df_BL.rename(columns={"Home Team":"H","Away Team":"A"},inplace=True)

In [8]:
df_BL.to_csv("t-liga.csv")
df_BL

                       H             A Result
0            Trabzonspor   Antalyaspor  1 - 0
1              Kasimpasa    Ankaragücü  3 - 2
2              Konyaspor  Istanbulspor  1 - 1
3            Kayserispor   Galatasaray  0 - 0
4             Pendikspor     Hatayspor  1 - 5
..                   ...           ...    ...
112             Besiktas    Samsunspor  1 - 1
113           Alanyaspor     Kasimpasa  1 - 2
114      Çaykur Rizespor    Fenerbahçe  2 - 5
115            Konyaspor   Antalyaspor  0 - 0
116  Istanbul Basaksehir   Trabzonspor  3 - 4

[839 rows x 3 columns]

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

#One Hot Encoder Timova - Domacin i Gost
onehot_encoder_domacin = OneHotEncoder(handle_unknown="ignore",drop="first")  # Ensure parameters are correct
kodiran_domacin = onehot_encoder_domacin.fit_transform(df_BL[["H"]]).toarray()
df_domacin = pd.DataFrame(kodiran_domacin,columns=onehot_encoder_domacin.get_feature_names_out(["H"]))

In [10]:
df_domacin.columns

Index(['H_Alanyaspor', 'H_Ankaragücü', 'H_Antalyaspor', 'H_Besiktas',
       'H_Bodrum', 'H_Eyüpspor', 'H_Fatih Karagümrük', 'H_Fenerbahçe',
       'H_Galatasaray', 'H_Gaziantep', 'H_Gençlerbirligi', 'H_Göztepe',
       'H_Hatayspor', 'H_Istanbul Basaksehir', 'H_Istanbulspor', 'H_Kasimpasa',
       'H_Kayserispor', 'H_Kocaelispor', 'H_Konyaspor', 'H_Pendikspor',
       'H_Samsunspor', 'H_Sivasspor', 'H_Trabzonspor', 'H_Çaykur Rizespor'],
      dtype='object')

In [11]:
df_domacin.shape

(839, 24)

In [12]:
#One Hot Encoder Timova - Gosti
onehot_encoder_gost = OneHotEncoder(handle_unknown="ignore",drop="first")  # Ensure parameters are correct
kodiran_gost = onehot_encoder_gost.fit_transform(df_BL[["A"]]).toarray()
df_gost = pd.DataFrame(kodiran_gost,columns=onehot_encoder_gost.get_feature_names_out(["A"]))

In [13]:
df_gost.shape

(839, 24)

In [14]:
#Sjedinjavanje tih osobina domacin i gost
df_jedan = pd.concat([df_domacin,df_gost],axis=1)
df_jedan

,H_Alanyaspor,H_Ankaragücü,H_Antalyaspor,H_Besiktas,H_Bodrum,H_Eyüpspor,H_Fatih Karagümrük,H_Fenerbahçe,H_Galatasaray,H_Gaziantep,...,A_Istanbulspor,A_Kasimpasa,A_Kayserispor,A_Kocaelispor,A_Konyaspor,A_Pendikspor,A_Samsunspor,A_Sivasspor,A_Trabzonspor,A_Çaykur Rizespor
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
835,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
836,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
837,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
838,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

## Transformisanje Rezultata u Varijablu - Y Varijable

#### Stvaranje Vrijednosti za Dvije Kolone iz Jedne Osobine/Kolone Rezultat

In [15]:
rez_dom = df_BL["Result"].str.slice(0,1)

In [16]:
rez_dom.head()

0    1
1    3
2    1
3    0
4    1
Name: Result, dtype: object

In [17]:
rez_gost = df_BL["Result"].str.slice(4,5)

In [18]:
rez_gost.head()

0    0
1    2
2    1
3    0
4    5
Name: Result, dtype: object

In [19]:
df_rezultatski = pd.concat([df_BL,rez_dom,rez_gost],axis=1)

In [20]:
#promjena naziva kolonama - spajanjem smo dobili kolone istih naziva
df_rezultatski.columns = ["H","A","Result","Rez1","Rez2"]
df_rezultatski

                       H             A Result Rez1 Rez2
0            Trabzonspor   Antalyaspor  1 - 0    1    0
1              Kasimpasa    Ankaragücü  3 - 2    3    2
2              Konyaspor  Istanbulspor  1 - 1    1    1
3            Kayserispor   Galatasaray  0 - 0    0    0
4             Pendikspor     Hatayspor  1 - 5    1    5
..                   ...           ...    ...  ...  ...
112             Besiktas    Samsunspor  1 - 1    1    1
113           Alanyaspor     Kasimpasa  1 - 2    1    2
114      Çaykur Rizespor    Fenerbahçe  2 - 5    2    5
115            Konyaspor   Antalyaspor  0 - 0    0    0
116  Istanbul Basaksehir   Trabzonspor  3 - 4    3    4

[839 rows x 5 columns]

In [21]:
#spremanje df_epl varijable za obradu osobine Result u excelu
df_rezultatski.to_csv("uredjivanje_skora_vani.csv")

## Uocavanje Indeksa Sezona - za Kasnije Floatiranje

In [22]:
#df_rezultatski[303:306] #sezona 23/4 od 0:306
#df_rezultatski[306:612] #sezona 24/5 od 306:612
#df_rezultatski[612:] #sezona25/6 od 612:

## Stvaranje Kolone Skor sa Vrijednostima - Ovdje

In [23]:
# Define a function to perform the conditional logic
def calculate_value(row):
    if row['Rez1'] > row['Rez2']:
        return 1
    elif row['Rez1'] < row['Rez2']:
        return -1
    else:  # row['Column1'] == row['Column2']
        return 0

In [24]:
# Apply the function to each row in the DataFrame and assign the result to a new column
df_rezultatski['Skor'] = df_rezultatski.apply(calculate_value, axis=1)
skor = df_rezultatski.drop(['H', 'A', 'Result', 'Rez1',"Rez2"],axis=1)

### Floatiranje Vrijednosti Kolone Skor - po Sezonama

#df_rezultatski[303:306] #sezona 23/4 od 0:306
#df_rezultatski[306:612] #sezona 24/5 od 306:612
#df_rezultatski[612:] #sezona25/6 od 612:

In [25]:
#sezona 23/4
skor23_4 = skor[0:306]
skor24_5 = skor[306:612]
skor25_6 = skor[612:]

In [26]:
#skor.head(3)
skor23_4["Skor"] = skor23_4["Skor"] * 0.71

C:\Users\amirb\AppData\Local\Temp\ipykernel_11832\3544292283.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  skor23_4["Skor"] = skor23_4["Skor"] * 0.71

In [27]:
skor24_5["Skor"] = skor24_5["Skor"] * 0.85

C:\Users\amirb\AppData\Local\Temp\ipykernel_11832\3136881136.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  skor24_5["Skor"] = skor24_5["Skor"] * 0.85

## Konačna kolona Skor - Sjedinjavanje Vrijednosti Sezona

In [28]:
skor = pd.concat([skor23_4, skor24_5, skor25_6], axis=0, ignore_index=True)

Provjera se vrši manuelno, gledanjem repa,glave i sredine ovog df-a

In [29]:
df_rezultatski = df_rezultatski.reset_index(drop=True)
skor = skor.reset_index(drop=True)

In [30]:
#provjera rezultata
finalna_provjera = pd.concat([df_rezultatski,skor],axis=1,ignore_index=True)
finalna_provjera = finalna_provjera.drop([3,4,5],axis=1)
finalna_provjera.columns = ["H","A","Rezultat","Skor"]

In [31]:
finalna_provjera.tail()

                       H            A Rezultat  Skor
834             Besiktas   Samsunspor    1 - 1   0.0
835           Alanyaspor    Kasimpasa    1 - 2  -1.0
836      Çaykur Rizespor   Fenerbahçe    2 - 5  -1.0
837            Konyaspor  Antalyaspor    0 - 0   0.0
838  Istanbul Basaksehir  Trabzonspor    3 - 4  -1.0

# Konačni df - Podaci su Sređeni

In [32]:
skor = skor.reset_index(drop=True)
df_jedan = df_jedan.reset_index(drop=True)

In [33]:
df_BL = pd.concat([df_jedan,skor],axis=1)

In [34]:
df_BL.head(5)

,H_Alanyaspor,H_Ankaragücü,H_Antalyaspor,H_Besiktas,H_Bodrum,H_Eyüpspor,H_Fatih Karagümrük,H_Fenerbahçe,H_Galatasaray,H_Gaziantep,...,A_Kasimpasa,A_Kayserispor,A_Kocaelispor,A_Konyaspor,A_Pendikspor,A_Samsunspor,A_Sivasspor,A_Trabzonspor,A_Çaykur Rizespor,Skor
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.71
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.71
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.71

In [35]:
#spremanje kodiranog niza podataka
df_BL.to_csv("kodirani_bl.csv")

## Razdvajanje Niza Podataka na Osobine za Predvidjanje i Ciljanu Osobinu

In [36]:
# X predvidjacke, y varijabla jeste Skor Osobina
X = df_BL.drop(["Skor"],axis=1)
y = df_BL["Skor"]

In [37]:
#razdvajanje podataka u treniranju i testirajuce nizove
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1,random_state=42)
X_train.head()

,H_Alanyaspor,H_Ankaragücü,H_Antalyaspor,H_Besiktas,H_Bodrum,H_Eyüpspor,H_Fatih Karagümrük,H_Fenerbahçe,H_Galatasaray,H_Gaziantep,...,A_Istanbulspor,A_Kasimpasa,A_Kayserispor,A_Kocaelispor,A_Konyaspor,A_Pendikspor,A_Samsunspor,A_Sivasspor,A_Trabzonspor,A_Çaykur Rizespor
422,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
360,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
538,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
657,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
72,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [38]:
#skaliranje ovih osobina
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[-0.23021426, -0.15177362, -0.23021426, ..., -0.21379048,
        -0.21379048, -0.24270565],
       [-0.23021426, -0.15177362, -0.23021426, ...,  4.67747666,
        -0.21379048, -0.24270565],
       [-0.23021426, -0.15177362, -0.23021426, ..., -0.21379048,
         4.67747666, -0.24270565],
       ...,
       [-0.23021426, -0.15177362, -0.23021426, ...,  4.67747666,
        -0.21379048, -0.24270565],
       [-0.23021426, -0.15177362, -0.23021426, ..., -0.21379048,
        -0.21379048, -0.24270565],
       [-0.23021426, -0.15177362, -0.23021426, ..., -0.21379048,
        -0.21379048, -0.24270565]])

In [39]:
#Spremanje tog Kodera - za Kasniju Upotrebu

with open("onehot_encoder_domacin.pkl","wb") as file:
    pickle.dump(onehot_encoder_domacin,file)
    
with open("onehot_encoder_gost.pkl","wb") as file:
    pickle.dump(onehot_encoder_gost,file)
    
with open("scaler.pkl","wb") as file:
    pickle.dump(scaler,file)

## Stvaranje Modela i Dobijanje Predikcije

In [40]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
#sledeca biblioteka se odnosi na stvaranje neurona iz kutije layers i alatom dense
from tensorflow.keras.layers import Dense

In [41]:
#konstrukcija modela
model=Sequential([
    Dense(16,activation="relu",input_shape=(X_train.shape[1],)), #HL1 connected to I/p - Skriveni Sloj 1 povezan sa I/p
    Dense(1,activation="tanh")
])

In [42]:
#Oblikovanje Modela 
model.compile(optimizer="adam",loss="mean_absolute_error",metrics=["mae"])
model.summary()

# Keras dokumentacija pojasnjava sta se dogodi sa razlicitim odabirom "loss" i drugih parametara

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 16)                784

 dense_1 (Dense)             (None, 1)                 17

=================================================================
Total params: 801
Trainable params: 801
Non-trainable params: 0
_________________________________________________________________

In [43]:
import datetime
#uspostavljanje Tensorboard-a, zapocinjanje treniranja
#TensorBoard sluzi samo za vizualizaciju svih logovanja koje izvrsim kod treniranja nekog modela
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

#log_dir varijabla koja osigurava da ostane zabinjezen trag svakog treniranja modela
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

#Uspostavljanje Early Stopping - sluzi za zaustavljanje treniranja ako se vrijednost gubitaka ne smanjuje
#bitni parametri su uneseni koji sluze poboljsanju funkcije ranog zaustavljanja treniranja modela...
early_stopping_callback = EarlyStopping(monitor="val_loss",patience=10,restore_best_weights=True)

In [44]:
#TRENIRANJE MODELA / Tovarenje Modela
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

history = model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=50,
    callbacks= [tensorflow_callback,early_stopping_callback]
)

Epoch 1/50
24/24 [==============================] - 6s 58ms/step - loss: 0.7389 - mae: 0.7389 - val_loss: 0.6495 - val_mae: 0.6495
Epoch 2/50
24/24 [==============================] - 0s 14ms/step - loss: 0.7044 - mae: 0.7044 - val_loss: 0.6271 - val_mae: 0.6271
Epoch 3/50
24/24 [==============================] - 0s 17ms/step - loss: 0.6724 - mae: 0.6724 - val_loss: 0.6054 - val_mae: 0.6054
Epoch 4/50
24/24 [==============================] - 1s 21ms/step - loss: 0.6448 - mae: 0.6448 - val_loss: 0.5834 - val_mae: 0.5834
Epoch 5/50
24/24 [==============================] - 1s 22ms/step - loss: 0.6181 - mae: 0.6181 - val_loss: 0.5698 - val_mae: 0.5698
Epoch 6/50
24/24 [==============================] - 0s 16ms/step - loss: 0.5944 - mae: 0.5944 - val_loss: 0.5585 - val_mae: 0.5585
Epoch 7/50
24/24 [==============================] - 0s 12ms/step - loss: 0.5737 - mae: 0.5737 - val_loss: 0.5490 - val_mae: 0.5490
Epoch 8/50
24/24 [==============================] - 0s 13ms/step - loss: 0.5567 - mae: 0.5567 - val_loss: 0.5428 - val_mae: 0.5428
Epoch 9/50
24/24 [==============================] - 0s 13ms/step - loss: 0.5413 - mae: 0.5413 - val_loss: 0.5377 - val_mae: 0.5377
Epoch 10/50
24/24 [==============================] - 0s 16ms/step - loss: 0.5285 - mae: 0.5285 - val_loss: 0.5325 - val_mae: 0.5325
Epoch 11/50
24/24 [==============================] - 0s 21ms/step - loss: 0.5163 - mae: 0.5163 - val_loss: 0.5282 - val_mae: 0.5282
Epoch 12/50
24/24 [==============================] - 0s 15ms/step - loss: 0.5060 - mae: 0.5060 - val_loss: 0.5233 - val_mae: 0.5233
Epoch 13/50
24/24 [==============================] - 0s 17ms/step - loss: 0.4949 - mae: 0.4949 - val_loss: 0.5179 - val_mae: 0.5179
Epoch 14/50
24/24 [==============================] - 0s 17ms/step - loss: 0.4867 - mae: 0.4867 - val_loss: 0.5165 - val_mae: 0.5165
Epoch 15/50
24/24 [==============================] - 1s 25ms/step - loss: 0.4791 - mae: 0.4791 - val_loss: 0.5151 - val_mae: 0.5151
Epoch 16/50
24/24 [==============================] - 0s 19ms/step - loss: 0.4723 - mae: 0.4723 - val_loss: 0.5159 - val_mae: 0.5159
Epoch 17/50
24/24 [==============================] - 0s 18ms/step - loss: 0.4679 - mae: 0.4679 - val_loss: 0.5153 - val_mae: 0.5153
Epoch 18/50
24/24 [==============================] - 1s 29ms/step - loss: 0.4622 - mae: 0.4622 - val_loss: 0.5160 - val_mae: 0.5160
Epoch 19/50
24/24 [==============================] - 1s 36ms/step - loss: 0.4564 - mae: 0.4564 - val_loss: 0.5209 - val_mae: 0.5209
Epoch 20/50
24/24 [==============================] - 1s 23ms/step - loss: 0.4521 - mae: 0.4521 - val_loss: 0.5217 - val_mae: 0.5217
Epoch 21/50
24/24 [==============================] - 1s 27ms/step - loss: 0.4483 - mae: 0.4483 - val_loss: 0.5259 - val_mae: 0.5259
Epoch 22/50
24/24 [==============================] - 1s 50ms/step - loss: 0.4437 - mae: 0.4437 - val_loss: 0.5297 - val_mae: 0.5297
Epoch 23/50
24/24 [==============================] - 1s 24ms/step - loss: 0.4402 - mae: 0.4402 - val_loss: 0.5286 - val_mae: 0.5286
Epoch 24/50
24/24 [==============================] - 1s 26ms/step - loss: 0.4375 - mae: 0.4375 - val_loss: 0.5277 - val_mae: 0.5277
Epoch 25/50
24/24 [==============================] - 1s 23ms/step - loss: 0.4339 - mae: 0.4339 - val_loss: 0.5289 - val_mae: 0.5289

In [45]:
#Procjena Rada Modela preko test podataka
test_loss, test_mae = model.evaluate(X_test,y_test)

3/3 [==============================] - 0s 7ms/step - loss: 0.5151 - mae: 0.5151

In [46]:
#spremanje modela
model.save("T-liga_float_model.h5")

In [47]:
#moze biti da skaliranje je neophodno, onda je potrebno i obnoviti test parametara modela, te iznova
#-trenirati model i na kraju ga ponovo spremiti.